server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always

  h2:
    console:
      enabled: true
